# Generated by Django 2.2.3 on 2020-08-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_paymentrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
